import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

function Home() {
  const [options, setOptions] = useState()
  const [selected, setSelected] = useState()

  useEffect(() => {
    setOptions(
      <>
        <div className={`${styles.option} ${selected === 'a' ? styles.select : null}`} onClick={() => setSelected('a')}>
          a
        </div>
        <div className={`${styles.option} ${selected === 'b' ? styles.select : null}`} onClick={() => setSelected('b')}>
          b
        </div>
        <div className={`${styles.option} ${selected === 'c' ? styles.select : null}`} onClick={() => setSelected('c')}>
          c
        </div>
        <div className={`${styles.option} ${selected === 'd' ? styles.select : null}`} onClick={() => setSelected('d')}>
          d
        </div>
      </>
    )

    window.addEventListener('focus', function () {
      console.log('Halaman mendapatkan fokus')
    })

    window.addEventListener('blur', function () {
      console.log('Halaman kehilangan fokus')
      setSelected(null)
    })
  }, [selected])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit.</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, sed distinctio? Sit consequuntur iure voluptatibus
          suscipit quisquam! Dolorem, doloribus mollitia.
        </p>
        <div className={styles.options}>{options}</div>
      </div>
    </>
  )
}

export default Home
